### ISSUE TITLE
[BUG] ULS throws an error when uls.py script is run

### ISSUE THREAD

**Issue by tomsilverberg** [akamai/uls#15]
**Describe the bug**
ULS throws an error when the uls.py script is run

**To Reproduce**
I have completed the Akamai Unified Log Streamer configuration on a test server, however I am getting an error when attempting to run the uls.py script.
Configuration:
1.	Configured the Akamai API key/secret pair and Akamai OPENAPI credentials in Akamai to create our .edgerc file.
2.	Verified that ports 9090, 9091, and 9092 are open and server has internet access
3.	Installed git and Python for Windows on test server
4.	Ran the git clone commands to create the needed git branches for eaa, etp, and mfa
5.	Setup the following python commands to pull the EAA logs:
      a.	python bin/uls.py --input eaa --feed admin --output tcp --host localhost --port 9090
      b.	python bin/uls.py --input eaa --feed access --output tcp --host localhost --port 9090
      c.	python bin/uls.py --input eaa --feed conhealth --output tcp --host localhost --port 9090

Issue:
It doesn’t matter which python commands I use I receive the following error:

Traceback (most recent call last):
  File "D:\Akamai\uls\bin\modules\UlsInputCli.py", line 249, in proc_create
    self.cli_proc = subprocess.Popen(cli_command,
  File "D:\python\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\python\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\lib\pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "D:\python\lib\pdb.py", line 1583, in _runscript
    self.run(statement)
  File "D:\python\lib\bdb.py", line 597, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "d:\akamai\uls\bin\uls.py", line 215, in <module>
    main()
  File "d:\akamai\uls\bin\uls.py", line 138, in main
    my_input.proc_create()
  File "D:\Akamai\uls\bin\modules\UlsInputCli.py", line 277, in proc_create
    f'{self.cli_proc.stderr.read().decode()}')
AttributeError: 'NoneType' object has no attribute 'stderr'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> d:\akamai\uls\bin\modules\ulsinputcli.py(277)proc_create()
-> f'{self.cli_proc.stderr.read().decode()}')

I used the python script debugger pdb to walk through the running of the uls.py script in an attempt to figure out why it’s failing.  It looks like the script finishes successfully, however it calls subprocess.py and that is where it fails.  Did a pdb walkthrough of subprocess.py but was unable to determine why it fails.

I have attached a copy of the .edgerc file for your reference.

**Expected behavior**
I expect the python script to run successfully and pull EAA logs

**Desktop (please complete the following information):**
 - OS: Windows Server 2016 Standard
 - Browser: Chrome 
 - Version 96.0.4664.93
 - Python ver 3.10.0
 - Git for Windows ver 2.34.1

**Comment by MikeSchiessl** [comment]
Hi @tomsilverberg ,

can you please try to work with the development branch instead of the "main" branch for testing? 
Actually, I think I might have sorted that issue recently - so it had no chance to walk into the main branch, yet ;) 

Please let me know if it is still existent, so I will have a closer look.

Best 
Mike

**Comment by tomsilverberg** [comment]
Thank you so much for getting back to me so quickly Mike.  I'll try the development branch and see if it helps.

Best regards,

Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

**Comment by tomsilverberg** [comment]
Hi Mike,

I downloaded the uls-development branch, ran the pip install command, and ran the git clone commands to create the needed branches.  I then ran the python script again and it still fails with the same error of no file found.

Here are the install and clone commands that I ran:
pip install -r bin/requirements.txt
git clone --depth 1 --single-branch https://github.com/akamai/cli-eaa.git ext/cli-eaa && pip install -r ext/cli-eaa/requirements.txt
git clone --depth 1 --single-branch https://github.com/akamai/cli-etp.git ext/cli-etp && pip install -r ext/cli-etp/requirements.txt
git clone --depth 1 --single-branch https://github.com/akamai/cli-mfa.git ext/cli-mfa && pip3 install -r ext/cli-mfa/requirements.txt

and here's the command run and error:
D:\Akamai\uls-development>python bin/uls.py --input eaa --feed admin --output tcp --host localhost --port 9090
Traceback (most recent call last):
  File "D:\Akamai\uls-development\bin\modules\UlsInputCli.py", line 257, in proc_create
    self.cli_proc = subprocess.Popen(cli_command,
  File "D:\python\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\python\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Akamai\uls-development\bin\uls.py", line 220, in <module>
    main()
  File "D:\Akamai\uls-development\bin\uls.py", line 143, in main
    my_input.proc_create()
  File "D:\Akamai\uls-development\bin\modules\UlsInputCli.py", line 287, in proc_create
    f'{self.cli_proc.stderr.read().decode()}')
AttributeError: 'NoneType' object has no attribute 'stderr'

Thanks for your help with sorting this out.

Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

From: Tom Silverberg
Sent: Wednesday, December 8, 2021 10:53 AM
To: akamai/uls ***@***.***>; akamai/uls ***@***.***>
Cc: Mention ***@***.***>; Mike DePorter ***@***.***>
Subject: RE: [akamai/uls] [BUG] ULS throws an error when uls.py script is run (Issue #15)

Thank you so much for getting back to me so quickly Mike.  I'll try the development branch and see if it helps.

Best regards,

Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

**Comment by MikeSchiessl** [comment]
Dang, ... could have been so easy :D 

So just to have everything for me to dig into, could you also please run the following for me and provide the output here:
`python bin/uls.py --version`

Along with your already provided data I might be able to dig a little deeper into to get some windows box set up for testing.

Best
Mike

**Comment by tomsilverberg** [comment]
Well this is interesting.  Here's what I get when I run this:

D:\Akamai\uls-development>python bin/uls.py --version
Akamai Unified Log Streamer Version information
ULS Version             1.2.1

EAA Version             n/a -> ([WinError 2] The system cannot find the file specified)
ETP Version             n/a -> ([WinError 2] The system cannot find the file specified)
MFA Version             n/a -> ([WinError 2] The system cannot find the file specified)

OS Plattform            Windows-10-10.0.14393-SP0
OS Version              10
Python Version          3.10.0
Docker Status           False
RootPath                D:\Akamai\uls-development

What's interesting is here's what I have in ext:
***@***.***

And here's the version in cli-eaa.  The file doesn't exist in the others:

***@***.***

Thanks and best regards,

Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

**Comment by MikeSchiessl** [comment]
Hey Tom,

I think I've got it sorted.
Actually, the issue consists out of two different things:

1) You need to provide a python3 executable.
I've added a [FAQ entry here](https://github.com/akamai/uls/blob/development/docs/FAQ.md#uls-on-windows-error-winerror-2-the-system-cannot-find-the-file-specified) - please pick one of the provided solutions.

2) There was a bug in ULS that caused the process to hang (probably forever)

The good news: if you do a git pull on the "development" branch, ULS should now run on windows and also provide logs.

```bash
c:\git\uls>python3 bin/uls.py -v
Akamai Unified Log Streamer Version information
ULS Version             1.2.1

EAA Version             0.4.4
ETP Version             0.3.5
MFA Version             0.0.6

OS Plattform            Windows-10-10.0.14393-SP0
OS Version              10
Python Version          3.10.1
Docker Status           False
RootPath                C:\git\uls
```

Just a side note: 
For testing purpose only, i recommend to use the "-o raw" output in order to see a direct reaction on my command ;)

Please let me know if this fixes your problem.

Best
Mike

**Comment by tomsilverberg** [comment]
Hi Mike,

Thank you so much for all your time and effort on this.  I really appreciate your assistance.

So it looks like both the Admin and Access scripts are working correctly and I am able to successfully pull data.  Awesome news!

I have a question regarding the Conhealth log script.  I have the necessary Open API credentials in my .edgerc file.  I ran the following command with -loglevel debug and had the output written to a file.  The issue is that nothing seems to get written to the file; the uls-eaa-health.log file remains empty.  Is this by design?

***@***.***
Here's the debug level:
D:\Akamai\uls-development>python3 bin/uls.py --loglevel debug --input eaa --feed conhealth --output file --filename d:\Akamai\uls-development\logs\uls-eaa-health.log
2021-12-09 11:55:56,747 ULS D Logging initialized
2021-12-09 11:55:56,747 ULS D UlsMonitoring monitoring thread started...
2021-12-09 11:55:56,747 ULS D UlsMonitoring sleeping 300 sec...
2021-12-09 11:55:56,747 ULS I UlsOutput Selected Output Type: FILE
2021-12-09 11:55:56,747 ULS D UlsTransformation - No Transformation loaded
2021-12-09 11:55:56,747 ULS I UlsInputCli - selected product: EAA
2021-12-09 11:55:56,747 ULS I UlsInputCli - selected feed: CONHEALTH
2021-12-09 11:55:56,747 ULS D Config file 'C:\Users\Tom.Silverberg/.edgerc' was found and is readable.
2021-12-09 11:55:56,747 ULS D Section 'default' found.
2021-12-09 11:55:56,747 ULS D Required configuration value 'host' found.
2021-12-09 11:55:56,747 ULS D Required configuration value 'client_token' found.
2021-12-09 11:55:56,747 ULS D Required configuration value 'client_secret' found.
2021-12-09 11:55:56,747 ULS D Required configuration value 'access_token' found.
2021-12-09 11:55:56,747 ULS I UlsInputCli - CLI Command:  python3 -u D:\Akamai\uls-development/ext/cli-eaa/bin/akamai-eaa --edgerc C:\Users\Tom.Silverberg/.edgerc --section default --user-agent-prefix ULS/1.2.1_EAA-CONHEALTH connector list --perf --tail --json
2021-12-09 11:55:56,763 ULS I UlsInputCli - started PID[8112]: python3 -u D:\Akamai\uls-development/ext/cli-eaa/bin/akamai-eaa --edgerc C:\Users\Tom.Silverberg/.edgerc --section default --user-agent-prefix ULS/1.2.1_EAA-CONHEALTH connector list --perf --tail --json
2021-12-09 11:55:57,763 ULS D UlsInputCli - Successful cycles for proc[8112]: 0
2021-12-09 11:55:57,763 ULS I UlsOutput preparing FILE output handler: SIZE , filename: d:\Akamai\uls-development\logs\uls-eaa-health.log encoding: utf-8 , maxbytes(SIZE): 52428800filetime(TIME): M , interval(TIME): 30
2021-12-09 11:55:57,763 ULS I UlsOutput - File output ready
2021-12-09 11:55:57,763 ULS D UlsInputCli - Successful cycles for proc[8112]: 1
{"dt": "2021-12-09T20:00:56.772376", "uls_product": "EAA", "uls_feed": "CONHEALTH", "uls_output": "FILE", "uls_runtime": 300, "event_count": 0, "event_rate": 0.0, "mon_interval": 300}
2021-12-09 12:00:56,772 ULS D UlsMonitoring sleeping 300 sec...
{"dt": "2021-12-09T20:05:56.792817", "uls_product": "EAA", "uls_feed": "CONHEALTH", "uls_output": "FILE", "uls_runtime": 600, "event_count": 0, "event_rate": 0.0, "mon_interval": 300}
2021-12-09 12:05:56,792 ULS D UlsMonitoring sleeping 300 sec...
{"dt": "2021-12-09T20:10:56.814194", "uls_product": "EAA", "uls_feed": "CONHEALTH", "uls_output": "FILE", "uls_runtime": 900, "event_count": 0, "event_rate": 0.0, "mon_interval": 300}
2021-12-09 12:10:56,814 ULS D UlsMonitoring sleeping 300 sec...



Thanks and best regards,

Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

**Comment by MikeSchiessl** [comment]
Hey Tom, 
this is good news !
Thanks for checking the fix. Happy that it works as expected.

I'll need to have a closer look towards that particular "conhealth" issue on Monday.

Have a great weekend
Mike

**Comment by tomsilverberg** [comment]
Sounds great.  Thanks so much Mike and have a nice weekend as well.


Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

**Comment by MikeSchiessl** [comment]
Hey Tom, 
hope you had some good weekend.

I just had a look at the "conhealth" and it works perfectly on my windows box (with the development version provided previously).
I am getting the connector health data into a file by running the following cmd
` python bin/uls.py -i eaa -f conhealth -o file  --filename C:/git/health.txt --edgerc c:/git/.edgerc -l debug`

**Comment by tomsilverberg** [comment]
Thanks for this information Mike.

I ran a similar command:

python3 bin/uls.py -i eaa -f conhealth -o file --filename d:\Akamai\uls-development\logs\uls-eaa-health.log --edgerc C:\Users\Tom.Silverberg\.edgerc -l debug

It runs fine, however it doesn't write anything to my file.  Based on the output, the event count is 0.  As it is pulling health data, I would think that there would be event health events.  Is there a way to check for events on Akamai Luna Control?

Here's a screenshot of the running of the script and the output file:
***@***.***

Thanks and best regards,

Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

**Comment by MikeSchiessl** [comment]
Hey Tom,

I've pressed publish too early this morning, please check the edited answer ;)


Best
Mike


Am 13.12.2021 17:38 schrieb tomsilverberg ***@***.***>:

Thanks for this information Mike.

I ran a similar command:

python3 bin/uls.py -i eaa -f conhealth -o file --filename d:\Akamai\uls-development\logs\uls-eaa-health.log --edgerc C:\Users\Tom.Silverberg\.edgerc -l debug

It runs fine, however it doesn't write anything to my file. Based on the output, the event count is 0. As it is pulling health data, I would think that there would be event health events. Is there a way to check for events on Akamai Luna Control?

Here's a screenshot of the running of the script and the output file:
***@***.***

Thanks and best regards,

Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

**Comment by tomsilverberg** [comment]
Thank for the additional details Mike.

Per Akamai Luna Control we have 12 connectors.

I ran your commands and it looks like I have an authorization issue.  I'll look into it and try to resolve.  I thought I had setup everything properly.

Here's what I see when I run the command:

D:\Akamai\uls-development>python3 ext/cli-eaa/bin/akamai-eaa --verbose --edgerc C:\Users\Tom.Silverberg\.edgerc connector list --perf
2021-12-13 10:12:56,571 root I Initialized with base_url https://akab-ko7jk7uunw3bsmrd-kd74qpwxfctjgluh.luna.akamaiapis.net/crux/v1/
2021-12-13 10:12:56,758 root I BaseAPI: GET response is HTTP 403
2021-12-13 10:12:56,774 charset_normalizer I ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
2021-12-13 10:12:56,774 charset_normalizer I ascii should target any language(s) of ['Latin Based']
2021-12-13 10:12:56,774 charset_normalizer I We detected language [('English', 1.0), ('Indonesian', 1.0), ('Simple English', 1.0)] using ascii
2021-12-13 10:12:56,774 charset_normalizer I ascii is most likely the one. Stopping the process.
2021-12-13 10:12:56,774 root I BaseAPI: GET response body: {
  "type": https://problems.luna.akamaiapis.net/-/pep-authz/deny,
  "title": "Forbidden",
  "status": 403,
  "detail": "The client does not have the grant needed for the request",
  "instance": https://akab-ko7jk7uunw3bsmrd-kd74qpwxfctjgluh.luna.akamaiapis.net/crux/v1/mgmt-pop/agents?expand=true&limit=256,
  "authzRealm": "5btl4pvqhdfxqb65.q75ym7gdvwcwauz7",
  "method": "GET",
  "serverIp": "104.99.69.223",
  "clientIp": "208.185.193.71",
  "requestId": "26a51f5",
  "requestTime": "2021-12-13T18:12:56Z"
}

#Connector-id,name,reachable,status,version,privateip,publicip,debug,last_upd,CPU%,Mem%,Disk%,NetworkMbps,do_total,do_idle,do_active
Total 0 connector(s)

Thank you so much for all your help with this.  You can go ahead an mark this bug as resolved.  I'll dig deeper and determine why I'm getting an authorization error.

Thanks and best regards,

Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

**Comment by MikeSchiessl** [comment]
Hey Tom,

feel free to open a ticket if you need any help on the creds ;).
Also, feel free to open another topic or contact me (mschiess@akamai.com) when you need additional support.
Thanks for confirming the close.

Best
Mike

**Comment by tomsilverberg** [comment]
Will do.  Thanks again for all your help with this Mike.  Appreciate your time.....


Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

**Comment by MikeSchiessl** [comment]
You're welcome Tom!

**Comment by tomsilverberg** [comment]
Hi Mike,

So I did a bit of troubleshooting regarding the authorization error that I get with connector access.  I know the documentation<https://github.com/akamai/uls/blob/main/docs/AKAMAI_API_CREDENTIALS.md#eaa-open-api-for-connector-health-feed> calls out granting read\write access to the Enterprise Application Access API, however I don't see that API listed so I cannot grant access:

***@***.***

Is it called something else now?  If not, is there a way to add it?

As an FYI, I created the API client and have created the credential about a week ago.  All of that information is in my .edgerc file

Here's the error I get when I attempt to run a connectivity test:
D:\Akamai\uls-development>python3 ext/cli-eaa/bin/akamai-eaa --verbose --edgerc C:\Users\Tom.Silverberg\.edgerc connector list --perf
2021-12-13 10:12:56,571 root I Initialized with base_url https://akab-ko7jk7uunw3bsmrd-kd74qpwxfctjgluh.luna.akamaiapis.net/crux/v1/
2021-12-13 10:12:56,758 root I BaseAPI: GET response is HTTP 403
2021-12-13 10:12:56,774 charset_normalizer I ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
2021-12-13 10:12:56,774 charset_normalizer I ascii should target any language(s) of ['Latin Based']
2021-12-13 10:12:56,774 charset_normalizer I We detected language [('English', 1.0), ('Indonesian', 1.0), ('Simple English', 1.0)] using ascii
2021-12-13 10:12:56,774 charset_normalizer I ascii is most likely the one. Stopping the process.
2021-12-13 10:12:56,774 root I BaseAPI: GET response body: {
  "type": https://problems.luna.akamaiapis.net/-/pep-authz/deny,
  "title": "Forbidden",
  "status": 403,
  "detail": "The client does not have the grant needed for the request",
  "instance": https://akab-ko7jk7uunw3bsmrd-kd74qpwxfctjgluh.luna.akamaiapis.net/crux/v1/mgmt-pop/agents?expand=true&limit=256,
  "authzRealm": "5btl4pvqhdfxqb65.q75ym7gdvwcwauz7",
  "method": "GET",
  "serverIp": "104.99.69.223",
  "clientIp": "208.185.193.71",
  "requestId": "26a51f5",
  "requestTime": "2021-12-13T18:12:56Z"
}

#Connector-id,name,reachable,status,version,privateip,publicip,debug,last_upd,CPU%,Mem%,Disk%,NetworkMbps,do_total,do_idle,do_active
Total 0 connector(s)

Thanks and best regards,

Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

**Comment by tomsilverberg** [comment]
Hi Mike S.

I believe I figured out the issue.  I had created the API Client and had set the owner to be our ITAppAdmin account.  I didn't realize that the API Client would be restricted to the level of access that the ITAppAdmin account has.  It looks like that account doesn't have access to EAA.

As a test, I created a test API Client under my account (full admin who has access to EAA) and see that I have the ability to grant access for EAA for that API Client.

For a permanent solution, I think we'll need to upgrade our IT App Admin account to include EAA.  That way the API Client will obtain the appropriate rights.

Again, thanks for all your help with this.  Merry Christmas and have a great holiday season.

Thanks and best regards,

Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

From: Tom Silverberg
Sent: Tuesday, December 14, 2021 11:34 AM
To: akamai/uls ***@***.***>; akamai/uls ***@***.***>
Cc: Mention ***@***.***>; Mike DePorter ***@***.***>
Subject: RE: [akamai/uls] [BUG] ULS throws an error when uls.py script is run (Issue #15)

Hi Mike,

So I did a bit of troubleshooting regarding the authorization error that I get with connector access.  I know the documentation<https://github.com/akamai/uls/blob/main/docs/AKAMAI_API_CREDENTIALS.md#eaa-open-api-for-connector-health-feed> calls out granting read\write access to the Enterprise Application Access API, however I don't see that API listed so I cannot grant access:

***@***.***

Is it called something else now?  If not, is there a way to add it?

As an FYI, I created the API client and have created the credential about a week ago.  All of that information is in my .edgerc file

Here's the error I get when I attempt to run a connectivity test:
D:\Akamai\uls-development>python3 ext/cli-eaa/bin/akamai-eaa --verbose --edgerc C:\Users\Tom.Silverberg\.edgerc connector list --perf
2021-12-13 10:12:56,571 root I Initialized with base_url https://akab-ko7jk7uunw3bsmrd-kd74qpwxfctjgluh.luna.akamaiapis.net/crux/v1/
2021-12-13 10:12:56,758 root I BaseAPI: GET response is HTTP 403
2021-12-13 10:12:56,774 charset_normalizer I ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
2021-12-13 10:12:56,774 charset_normalizer I ascii should target any language(s) of ['Latin Based']
2021-12-13 10:12:56,774 charset_normalizer I We detected language [('English', 1.0), ('Indonesian', 1.0), ('Simple English', 1.0)] using ascii
2021-12-13 10:12:56,774 charset_normalizer I ascii is most likely the one. Stopping the process.
2021-12-13 10:12:56,774 root I BaseAPI: GET response body: {
  "type": https://problems.luna.akamaiapis.net/-/pep-authz/deny,
  "title": "Forbidden",
  "status": 403,
  "detail": "The client does not have the grant needed for the request",
  "instance": https://akab-ko7jk7uunw3bsmrd-kd74qpwxfctjgluh.luna.akamaiapis.net/crux/v1/mgmt-pop/agents?expand=true&limit=256,
  "authzRealm": "5btl4pvqhdfxqb65.q75ym7gdvwcwauz7",
  "method": "GET",
  "serverIp": "104.99.69.223",
  "clientIp": "208.185.193.71",
  "requestId": "26a51f5",
  "requestTime": "2021-12-13T18:12:56Z"
}

#Connector-id,name,reachable,status,version,privateip,publicip,debug,last_upd,CPU%,Mem%,Disk%,NetworkMbps,do_total,do_idle,do_active
Total 0 connector(s)

Thanks and best regards,

Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

**Comment by MikeSchiessl** [comment]
Hey Tom, 
this is, first of all, brilliant news 😉 

I wanted to revisit your ticket tomorrow, as I was blocked by adding features to the new ULS version 1.3.0 (available soon) 
 
Yes, I think you’re totally right regarding the RBAC adjusting. 
You might raise a ticket within Akamai Control Center if you need any assistance in getting this done.

I am glad you sorted this topic and are now able to even grab the health_status data through ULS.

Thanks for your wishes, have a great break as well, and enjoy the Christmas holidays.
I wish you a lot of geeky presents under the xmas tree, I’ll get myself into some additional “home control” stuff (hopefully Santa reads this 😃)

**Comment by tomsilverberg** [comment]
Hi Mike,

So, I was able to make some changes to the role that our ITAppAdmin account has and granted it access to EAA.  I am now able to see Enterprise Application Access as a selectable API for the API Client.  I granted it read only access and now the ConHealth EAA script works fine.  I tested to make sure I didn’t break anything with the other two (shouldn’t have since they use a different means of access) and all good.  I can now say that all three scripts (admin, access, and conhealth) work great and am able to write to files locally on my test server.  So that’s excellent news.  The next hurdle will be to integrate this with Splunk, which should work with a TCP input on a heavy forwarder.

Thank you for the holiday wishes as well and likewise, I hope you get a lot of nice geeky gifts too….  Who knows what my wife and daughters have bought for me.  Looking forward to some time off over Christmas.  We’re planning a trip down to Lake Tahoe in California to visit with my family.

Well, it’s getting pretty cold here in the Seattle area….  Perhaps snow soon.  Based on my sleuthing (looked you up in LinkedIn), you’re located in Bavaria, Germany!  Super cool!

Thanks and best regards,

Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

**Comment by tomsilverberg** [comment]
Hi Mike S.,

Hope all is well with you and that you had a nice holiday break.

I’m sure you’ve moved on to other things however I have a question that hopefully you can help with.  I was able to configure the Python scripts to send the Akamai EAA logs to our Splunk Heavy forwarder and it all works great… until the data loads into Splunk Cloud.  I had configured the TCP inputs to listen on specific ports and had set the sourcetype as _json.  The data does successfully load into Splunk Cloud, however it doesn’t seem to get parsed correctly.  We believe this may be because the data is being sent to Splunk as a data stream blob and Splunk isn’t able to determine the breaks.

We’ve tried testing on our Splunk Heavy Forwarder using a sample of the data written to file and the Heavy Forwarder is able to parse the data correctly, it’s only when we try to send it via the TCP inputs that it’s not able to parse.

In Splunk Cloud, the data looks like this:

***@***.***

Any thoughts would be very helpful.

Thanks and best regards,

Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

From: Tom Silverberg
Sent: Wednesday, December 15, 2021 12:04 PM
To: akamai/uls ***@***.***>; akamai/uls ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [akamai/uls] [BUG] ULS throws an error when uls.py script is run (Issue #15)

Hi Mike,

So, I was able to make some changes to the role that our ITAppAdmin account has and granted it access to EAA.  I am now able to see Enterprise Application Access as a selectable API for the API Client.  I granted it read only access and now the ConHealth EAA script works fine.  I tested to make sure I didn’t break anything with the other two (shouldn’t have since they use a different means of access) and all good.  I can now say that all three scripts (admin, access, and conhealth) work great and am able to write to files locally on my test server.  So that’s excellent news.  The next hurdle will be to integrate this with Splunk, which should work with a TCP input on a heavy forwarder.

Thank you for the holiday wishes as well and likewise, I hope you get a lot of nice geeky gifts too….  Who knows what my wife and daughters have bought for me.  Looking forward to some time off over Christmas.  We’re planning a trip down to Lake Tahoe in California to visit with my family.

Well, it’s getting pretty cold here in the Seattle area….  Perhaps snow soon.  Based on my sleuthing (looked you up in LinkedIn), you’re located in Bavaria, Germany!  Super cool!

Thanks and best regards,

Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

**Comment by MikeSchiessl** [comment]
Hey Tom, happy new year !

Sorry for the delay but I've just returned from my holidays ;) 

Yes, I think the line ending is a "known" issue which I've documented in the SPLUNK section here:

https://github.com/akamai/uls/tree/main/docs/SIEM/SPLUNK

Please give it a try and let me know if this worked or not.
ULS also provides you with another way to configure line breaks - you might want to have a look into the configuration file ;) 

Best 
Mike

**Comment by tomsilverberg** [comment]
Thank you so much for your response Mike.  I hope you had a nice holiday break... I sure did.

So, I found that your solution works properly, however it seems to be inconsistent.  Some records are successfully getting parsed but some are not.

We decided to take a different approach and use an HTTP Event Collector (HEC) in Splunk rather than TCP and we find that it works beautifully.  I am now able to import Admin, Access, and ConHealth logs into Splunk and the json is parsing correctly for all three.

Well thank you for tagging along on this adventure....  It definitely has been fun and educational.  If you're ever out in the Seattle, WA area let me know; I owe you a beer for all your help.

Thanks and best regards,

Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]

**Comment by MikeSchiessl** [comment]
Hi Tom, thanks - i'll definitely give you a ping if I pop into the Seattle area - but nevermind, I am always happy to help !!! 

Anyway - to get things sorted can you provide the feed that was not parsed correctly? I am running several input streams, preferably on TCP (performance), and never had any issues. Maybe I missed some change on the API side or there is some bug I never ran into - so if you're able to share additional intel - I am happy to get this sorted.

I am really happy that ULS is now properly working on your side - brilliant !!!! 


Best regards
Mike

**Comment by tomsilverberg** [comment]
Hi Mike,

Thanks for your response.  We noticed this occurring for the EAA Access and ConHealth logs.

Here's an example of Access where the data was not parsed correctly followed by one that was successfully parsed:

***@***.***
At that time we were only testing with EAA Access.

Here's an example with ConHealth (I had the fix applied to Access, Admin, and ConHealth feeds in my props.conf):
***@***.***

Also, just wanted to give you a bit of background around our infrastructure.  We were testing the Python EAA scripts from an on-prem Splunk task server.  The TCP inputs were configured on an on-prem Splunk Heavy Forwarder and set to only listen for data on ports 9090, 9091, and 9092 on the Splunk task server.  The Heavy Forwarder would then send the data on to Splunk Cloud.  Not too sure if it was the HF that was causing issues.

But anyway, we're happy with the HTTP solution and, since our volume isn't very large, I think the performance impact should be acceptable.  The HTTP solution also takes the HF out of the picture since we're using a HEC directly on Splunk Cloud.

Thanks and best regards,

Tom M. Silverberg
DevOps Engineer
IT Application Administrators
***@***.******@***.***>
425-657-7597
[email-sig-logo (2)]
