### ISSUE TITLE
[BUG] ULS not fetching data from SIA (ETP)

### ISSUE THREAD

**Issue by LuiRodriAKM** [akamai/uls#40]
**Describe the bug**
ULS is receiving 0 events, although more than 5000 events are being generated on the SIA report in Akamai Control Center

**To Reproduce**  

- Deploy ULS 1.6.3 in CentOS with SIA (ETP) Version: 0.4.0 and Python 3.11.2
- Performed manual installation, because the automatic one had issues with python versions and the required libraries (requirements.txt)
- Double checked the firewall has the following TCP ports open: 9090, 9091 and 9092

**Expected behavior**  
ULS to fetch data from SIA(ETP) and send them to Qradar via TCP

**Screenshots**  

ULS Running in debug mode Print 1
![Debug mode](https://github.com/akamai/uls/assets/125676671/c878e338-f57f-407d-813f-68a5f628c1c9)

ULS Running in debug mode Print 2
![Debug mode 2](https://github.com/akamai/uls/assets/125676671/77b248a4-9a2b-469d-8cb5-642e76e0db37)

CentOS port usage
![Port Usage](https://github.com/akamai/uls/assets/125676671/fb775164-1c29-4213-8a1e-fcc01e96ce85)

Software Versions
![Versions](https://github.com/akamai/uls/assets/125676671/2cc9b1f5-9d4b-4d51-9c62-8460780ed7be)

**ULS Version output**  
please run the following and attach the output here.

ULS was running on the customer machine, so I only got the print screen above

**Comment by MikeSchiessl** [comment]
Hi @LuiRodriAKM ,

this is weird, if there are any logs on the Control Center, you should be able to retrieve them via ULS .

So for a first start, can we run ULS just in the "raw" mode, to see if there is anything coming into ULS. 
```
/root/uls/bin/uls.py --input etp --feed DNS --output raw
```
This will fetch the logs and just send them to the local console output.
If nothing is there, we might need to dig into the CLI level for additional debugging.

The cool thing is, ULS running in '--loglevel DEBUG' will give you the full CLI command line and you can chuck in  the CLI  '--debug' command right after the binary

Heres an example of the CLI command
![image](https://github.com/akamai/uls/assets/77062930/fad2bbf7-6cd7-41ee-b029-82ab3812865b)

Anyways, feel free to reach out to me on WebEx so we can have a debugging session if required.

**Comment by MikeSchiessl** [comment]
Hi @LuiRodriAKM ,

is this ticket still relevant ?
Please fee free to reach out to me at any tome so I can help you get this issue sorted.

**Comment by MikeSchiessl** [comment]
no feedback for now - closing this
