### ISSUE TITLE
[BUG] - Over time the query time in the logs becomes further and further behind UTC

### ISSUE THREAD

**Issue by chris-bristow-maersk** [akamai/uls#50]
**Describe the bug**

**To Reproduce**  
In our environment we start ULS service
tail -f rsyslog (where logs are being stored)
Compare the server time (UTC via NTP) and the query time in the logs
Over time the difference between these becomes longer and longer

Looking in our logs we see an event_rate which was (Oct 10th) over 1000, and today is sub-100 (83)

Is there some sort of API throttling? 
Are we pulling more logs than API can handle?
D we need to look at increasing amount of logs we can pull or reduce the frequency of how often we pull logs? etc

**Expected behavior**  
The time difference when the service is first started is around 5-10 minutes and this is the expected behaviour going forward.

**Screenshots**  
![ETP logs and event rate](https://github.com/akamai/uls/assets/101122906/3444bace-b322-46c4-ad05-13b3bedab2cf)
![ETP log volumes](https://github.com/akamai/uls/assets/101122906/c8291260-e9bd-4fef-901b-42eb1fcce43f)
![ETP event rate comparison](https://github.com/akamai/uls/assets/101122906/26c4df2e-0e2f-4af0-9faa-3225714b198d)

**ULS Version output**  
please run the following and attach the output here.
[root@akamaietpvm1 logcollector]# /root/uls/bin/uls.py --version
Akamai Unified Log Streamer Version information
ULS Version1.6.6

EAA Versionn/a
ETP Version0.4.2
MFA Versionn/a
GC Versionn/a
LINODE Versionn/a

OS PlattformLinux-4.18.0-305.88.1.el8_4.x86_64-x86_64-with-redhat-8.4-Ootpa
OS Version4.18.0-305.88.1.el8_4.x86_64
Python Version3.6.8
Container StatusFalse
RootPath /root/uls
TimeZone (UTC OFST) UTC (0.0)
Installation ID VFo5RlMxLTIwMjMwOTExLTEuNi42
```

**Additional context**

**Comment by MikeSchiessl** [comment]
Hi @chris-bristow-maersk  - thanks for raising this.
I am seeing the issue seems to have been solved through an API improvement conducted by our T3 team. 
Can you please confirm this topic is solved for now ?

**Comment by chris-bristow-maersk** [comment]
Hi Mike, as per my last email, yes the throughput for pulling the events has dramatically increased since the backend changes. We will of course keep monitoring
Sure this case can be closed now
thanks

**Comment by MikeSchiessl** [comment]
Thank you @chris-bristow-maersk  - this is much appreciated
