### ISSUE TITLE
[FEATURE] Collect additional values via ULS for "client-based" EAA applications

### ISSUE THREAD

**Issue by 2013airotciv** [akamai/uls#55]
**Is your feature request related to a problem? Please describe.**

Currently the logging provided by ULS for our EAA applications is lacking certain values:
Both the following fields contain a value of **null**: "con_ip" and "con_srcport".
All the following fields contain a value of **Other**: "json.device_os", "json.device_type" and "json.user_agent".

This is a problem for us as we do require this logging for additional visibility.

**Describe the solution you'd like**

As all of our applications are custom client-based ones in EAA, we would like the above fields to be properly logged by ULS with their real values.

The very big concern here are the con_ip and con_srcport, but the device_os, device_type and user_agent would all be very nice to have as well.

**Describe alternatives you've considered**

As an alternative we've been exploring developing our own tool leveraging the EAA API to log this information. The problem here are the con_ip and con_srcport fields as those don't seem to be collected for the client-based applications.

Another thing we have discussed internally is migrating all of our client-based apps to client-less applications. This however is a really undesirable option as we have near a 1000 apps with various configurations.

**Additional context**

We were previously advised that this is indeed a feature that the ULS team is working on - is this really the case? Is there any information as to when this will be available to end customers like ourselves?

**Comment by MikeSchiessl** [comment]
Hi @2013airotciv, 
thanks for filing a feature request.

Basically, ULS itself is just a simple "wrapper",  consuming the logging APIs of the different Akamai products on one side and delivering it via different protocols on the other side (adding a couple of nifty features as well ;) ).

Having said that, ULS itself is facing the same restrictions, as you would with a native request against the API. Therefore we have no additional or enhanced data sets than what is being delivered today.
You can also consult the [related techdocs  ](https://techdocs.akamai.com/eaa/docs/data-feed-siem#access-logs) to find out, which fields are present in which mode of operation (client/clientless).
![image](https://github.com/akamai/uls/assets/77062930/34cc13a4-fff9-40f1-bd88-3326fd42e932)


So what you have observed being served directly by the API, is identical to what ULS can retrieve.

As ULS is just a dumb "transmitter", we're not able to fulfill your feature request on ULS side. 
Anyhow, I propose two different streams:
- please go and file a feature request via the Akamai product ticket system (AkaTec)
- I'll also try to get some additional intel if there are any ongoing operations to deliver additional fields that might statisfy your request.

I am really sorry that  I am not able to deliver a more satisfying answer by now.

Best 
Mike

**Comment by 2013airotciv** [comment]
Thank you Mike, I've raised a ticket with AkaTec in regards to this. Hopefully it get's added to the API at some point.
If you have any/some additional info - add it here, otherwise - feel free to close this out.

**Comment by MikeSchiessl** [comment]
Thank you for confirming @2013airotciv.
Feel free to add me as a watcher or drop my name on the ticket - happy to support from my end, wherever I can.

As I can't do much on this ticket from ULS side, I am closing it, as you proposed. Feel free to raise another one if you have any other questions.
