### ISSUE TITLE
 Akamai ETP Issue with date/time and gap in log chart due to leap year

### ISSUE THREAD

**Issue by Ginni-Bhatia** [akamai/uls#56]
**Describe the bug**
 Noticed gap in log chart for Akamai ETP logs, also noticed that the date/time is in March 2024 instead of 29th Feb 2024.

**To Reproduce**  
Check the logs generated by Akamai ET after 28th Feb midnight or
check the time sync for Akamai ETP

**Expected behavior**  
For today i.e. Feb 29th 2024, Logs should be dated 29th Feb 2024 however they are dated 1st March 2024

**Screenshots**  

![image](https://github.com/akamai/uls/assets/101125352/e3dfe068-cfce-453d-bc50-8554407a7a16)

**Additional context**  
Checked logs in Sentinel and found that after 28th Feb Midnight the next date was 1st March, meaning there is no log loss however leap year date is not reflected in Akamai ETP logs

![image](https://github.com/akamai/uls/assets/101125352/568239e1-668e-4566-b7a6-5bffd95fe037)

**Comment by bitonio** [comment]
Hi,

thanks for reporting the issue.
One Q before we dig into this, what is the date used to calculate these charts? Is it coming from the etp log payload (that would be the api), or a different field?

I would love to see one of these message binned to march 1st. Maybe not here for confidentiality, you can use androcho (@t) akamai (d0t) com

**Comment by MikeSchiessl** [comment]
As discussed on the email threat, the issue was tackled down to a non ULS releated leap year bug
closing the ticket
