### ISSUE TITLE
[BUG] Cannot pull the EAA access logs through docker

### ISSUE THREAD

**Issue by ravikannancsap** [akamai/uls#63]
**Describe the bug**
When I run Akamai ULS in docker container, it is not pulling in any of the EAA logs. I was able to run the Python program locally which was able to access the logs with the same .edgerc file.

**To Reproduce**  
1. build the akamai-uls:latest image
2. run using the instruction for docker in the documentation
3. I can see the application running but its not able to get any logs from the server

**Expected behavior**  
The application should be pulling in the access logs and then forward it as set up. I tried various ways, including, logging to the file system, raw and fowarding to a https endpoint

**Screenshots**  
N/A

**ULS Version output**  
Traceback (most recent call last):
  File "/opt/akamai-uls/uls/bin/uls.py", line 28, in <module>
    import modules.UlsOutput as UlsOutput
  File "/opt/akamai-uls/uls/bin/modules/UlsOutput.py", line 21, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Additional context**  
Please reference case ID#F-CS-8643421

**Comment by MikeSchiessl** [comment]
Hi @ravikannancsap,

thanks for raising this issue. I have already been working on a fix on that release, as I tried to state in the release Readme:
https://github.com/akamai/uls/releases/tag/1.7.4

If you want, you can use the latest development tag from the docker registry which should include an already fixed version .
I am going to release the fixed version within the next couple of days.

Best regards
Mike

**Comment by ravikannancsap** [comment]
Hi @MikeSchiessl, I got it working with 1.7.3. I was using the latest tag so I think that tag is still not fixed in docker registry.

**Comment by MikeSchiessl** [comment]
Hi @ravikannancsap, thanks for the update.
The "patched" forward version is currently available under the development tag in dockerhub:
```
docker pull akamai/uls:development
```

I'll release the patched version in the next couple of days ;)

**Comment by MikeSchiessl** [comment]
Hi @ravikannancsap ,

I am happy to announce that we just released the bugfixes version in ULS v1.7.5
https://github.com/akamai/uls/releases/tag/1.7.5

Best
Mike
