### ISSUE TITLE
Improve JSON Log Escaping to Ensure Compatibility with Third-Party Tools like Kibana

### ISSUE THREAD

**Issue by sethumadhav07** [akamai/uls#71]
**Is your feature request related to a problem? Please describe.**
I'm facing issues when certain JSON logs are emitted. They are not properly escaped, which prevents them from being ingested into third-party tools like Kibana. This mainly happens with specific log messages that include JSON data as part of the log description, making them incompatible with certain parsers.

uls-log format in the command:

```
--ulslogformat '{\"@timestamp\": \"%(asctime)s\", \"level\": \"%(levelname)s\", \"type\": \"log\", \"data_version\": 2, \"application\": \"akamai-uls\", \"description\": \"%(message)s\", \"roletype\": \"akauls\"}' --ulslogdatefmt "%Y-%m-%dT%H:%M:%S%z"
```

Here are some examples of logs causing the issue:

```
{"@timestamp": "2024-09-16T21:02:19+0000", "level": "DEBUG", "type": "log", "data_version": 2, "application": "akamai-uls", "description": "<IN> b'{"dir_id": "dir://kUz63dPlTcqPbWvhOrZokw", "service": "Cloud", "name": "Cloud Directory", "datetime": "2024-09-16T21:02:19.135434+00:00", "enabled": true, "connector_count": 0, "directory_status": "no_connector", "group_count": 2, "user_count": 0, "last_sync": "2024-02-13T19:49:39.568801"}\n'", "roletype": "akauls"}
```

```
{"@timestamp": "2024-09-16T21:02:17+0000", "level": "INFO", "type": "log", "data_version": 2, "application": "akamai-uls", "description": "FILTER pattern has been specified: .*"name": "test-directory".* - will only output matches", "roletype": "akauls"}
```

```
{"@timestamp": "2024-09-16T21:02:19+0000", "level": "INFO", "type": "log", "data_version": 2, "application": "akamai-uls", "description": "SKIPPED LINE due to FILTER rule .*"name": "test-directory".*", "roletype": "akauls"}
```

```
{"@timestamp": "2024-09-16T21:02:19+0000", "level": "DEBUG", "type": "log", "data_version": 2, "application": "akamai-uls", "description": "<OUT> b'{"dir_id": "dir://suy-WvX8Sii4c5mRvtoX9w", "service": "ActiveDirectory", "name": "test-directory", "datetime": "2024-09-16T21:02:19.135434+00:00", "enabled": true, "connector_count": 1, "directory_status": "ok", "group_count": 6, "user_count": 155, "last_sync": "2024-09-16T20:48:31.400388", "connectors": [{"agent_infra_type": 1, "created_at": "2024-05-08T19:29:06.162755", "name": "test-eaa-connector-01", "package": 3, "reach": 1, "state": 6, "status": 1, "uuid_url": "VyLY5K28ScORzjBjXjSM9A"}]}'", "roletype": "akauls"}
```

```
{"@timestamp": "2024-09-16T21:02:19+0000", "level": "INFO", "type": "log", "data_version": 2, "application": "akamai-uls", "description": "SKIPPED LINE due to FILTER rule .*"name": "test-directory".*", "roletype": "akauls"}
```

```
{"@timestamp": "2024-09-16T21:02:19+0000", "level": "DEBUG", "type": "log", "data_version": 2, "application": "akamai-uls", "description": "SKIPPED the following LOG_LINE due to FILTER match: b'{"dir_id": "dir://CXLv14gtT3CSlJm81OGsig", "service": "ActiveDirectory", "name": "test-directory", "datetime": "2024-09-16T21:02:19.135434+00:00", "enabled": true, "connector_count": 2, "directory_status": "ok", "group_count": 4, "user_count": 687, "last_sync": "2024-09-16T14:48:33.892955", "connectors": [{"agent_infra_type": 1, "created_at": "2024-06-13T20:44:11.797531", "name": "test-eaa-connector-01", "package": 1, "reach": 1, "state": 6, "status": 1, "uuid_url": "fjPLhicGRGWJmFQnL-0NGA"}, {"agent_infra_type": 1, "created_at": "2024-08-06T20:07:24.418049", "name": "test-eaa-connector-02", "package": 1, "reach": 1, "state": 6, "status": 1, "uuid_url": "kb6n2670SdeX3XN_-4_MeA"}]}'", "roletype": "akauls"}
```

Logs like the ones above cause parsing issues due to unescaped double quotes and other characters.

**Describe the solution you'd like**
The issue can be resolved by properly escaping the JSON data within log messages before they are emitted. Specifically, double quotes (`"`) inside the JSON should be escaped to avoid conflicts. For example:

```
filter_escaped = uls_args.filter.replace('"', '\\"')
aka_log.log.info(f"FILTER pattern has been specified: {filter_escaped} - will only output matches")
```

```
if uls_args.debugloglines:
    escaped_data = input_data.decode('utf-8').replace('"', '\\"')
    aka_log.log.debug(f"<IN> {escaped_data}")
```

```
log_line_escaped = log_line.decode('utf-8').replace('"', '\\"')
aka_log.log.debug(f"SKIPPED the following LOG_LINE due to FILTER match: {log_line_escaped}")
```

**Describe alternatives you've considered**
A possible alternative is modifying the downstream tools like Kibana to handle these malformed logs. However, this is not ideal, as proper log formatting should be ensured at the source to maintain consistency and compatibility across various log analysis platforms.

**Additional context**
This issue affects integrations with tools like Kibana that rely on correctly formatted JSON logs. Proper escaping would make these logs more universally compatible with log aggregation and analysis tools, preventing ingestion failures or parsing errors.

**Comment by MikeSchiessl** [comment]
Hi @sethumadhav07 , 

thanks for raising this. I do agree a 100% that this should be fixed inline - rather than "break-fixing" the receiving ends.

I'll have a look at this once I find some. 
From a brief glimpse, i would say your above proposal might work perfectly - so if you want to get it into the develop branch asap, feel free to fire a PR - happy to merge


Best Mike

**Comment by sethumadhav07** [comment]
hi @MikeSchiessl could you please review the PR?

**Comment by MikeSchiessl** [comment]
Hey @sethumadhav07 , thank you so much for your PR.

I have merged it into my v1.8.3 development branch and you will find your fixes in the upcoming version.
You can also find the "development" version in the development branch of this repo.

Best regards
Mike

**Comment by sethumadhav07** [comment]
Thanks @MikeSchiessl. when can I expect the release of upcoming version?

**Comment by MikeSchiessl** [comment]
I am planning to drop the new version (likely only containing your fix :D) somewhere next week.
I hope that's ok for you.

Best
Mike

**Comment by sethumadhav07** [comment]
Sure, sounds good to me. Thanks

**Comment by MikeSchiessl** [comment]
Hey @sethumadhav07 , happy Monday.
As promised, here is the latest ULS version: [v1.8.3](https://github.com/akamai/uls/releases/tag/1.8.3)

Thanks again for your contribution - this is much appreciated!
